package pe.com.equifax.ws.creditreport.endpoint.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import pe.com.equifax.creditreport.ws.endpoint.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-05-02T12:30:40.530-05:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "CreditReportPortService",
                  wsdlLocation = "https://ws.equifax.com.pe/CreditReportService/Endpoint?wsdl",
                  targetNamespace = "http://impl.endpoint.creditreport.ws.equifax.com.pe/")
public class CreditReportPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.endpoint.creditreport.ws.equifax.com.pe/", "CreditReportPortService");
    public final static QName CreditReportPort = new QName("http://impl.endpoint.creditreport.ws.equifax.com.pe/", "CreditReportPort");
    static {
        URL url = null;
        try {
            url = new URL("https://ws.equifax.com.pe/CreditReportService/Endpoint?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreditReportPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://ws.equifax.com.pe/CreditReportService/Endpoint?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreditReportPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreditReportPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditReportPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreditReportPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreditReportPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreditReportPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Endpoint
     */
    @WebEndpoint(name = "CreditReportPort")
    public Endpoint getCreditReportPort() {
        return super.getPort(CreditReportPort, Endpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Endpoint
     */
    @WebEndpoint(name = "CreditReportPort")
    public Endpoint getCreditReportPort(WebServiceFeature... features) {
        return super.getPort(CreditReportPort, Endpoint.class, features);
    }

}
