package pe.com.equifax.creditreport.ws.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-05-02T12:30:40.468-05:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://ws.creditreport.equifax.com.pe/endpoint", name = "Endpoint")
@XmlSeeAlso({pe.com.equifax.creditreport.ws.document.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Endpoint {

    @WebMethod(operationName = "GetReporteOnline")
    @WebResult(name = "GetReporteOnlineResponse", targetNamespace = "http://ws.creditreport.equifax.com.pe/endpoint", partName = "parameters")
    public GetReporteOnlineResponse getReporteOnline(
        @WebParam(partName = "parameters", name = "GetReporteOnline", targetNamespace = "http://ws.creditreport.equifax.com.pe/endpoint")
        GetReporteOnline parameters
    ) throws EquifaxInterfaceException_Exception;

    @WebMethod(operationName = "GetReporteHistorico")
    @WebResult(name = "GetReporteHistoricoResponse", targetNamespace = "http://ws.creditreport.equifax.com.pe/endpoint", partName = "parameters")
    public GetReporteHistoricoResponse getReporteHistorico(
        @WebParam(partName = "parameters", name = "GetReporteHistorico", targetNamespace = "http://ws.creditreport.equifax.com.pe/endpoint")
        GetReporteHistorico parameters
    ) throws EquifaxInterfaceException_Exception;
}
